displayName=RuneWatch SA
description=Shows players on the RuneWatch South America watchlist.
tags=scam, watch, list, south america, sa, runewatch
author=Seacin
plugins=com.runewatchsa.RuneWatchSAPlugin
build=standard