repository=https://github.com/Th3mike/runewatch-sa-plugin
display_name=RuneWatch SA
description=Shows players on the RuneWatch South America watchlist.
tags=scam, watch, list, south america, sa, runewatch
author=Seacin
plugins=com.runewatchsa.RuneWatchSAPlugin
